// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/auth" | "/drafts" | "/drafts/[draftId]"
type AppRouteHandlerRoutes = "/api/account" | "/api/admin/sync-leaguepedia" | "/api/chat" | "/api/chat/metrics" | "/api/chat/reactions" | "/api/chat/upload" | "/api/cron/drafts" | "/api/drafts" | "/api/drafts/[draftId]" | "/api/drafts/[draftId]/pick" | "/api/drafts/[draftId]/presence" | "/api/drafts/[draftId]/status" | "/api/drafts/metrics" | "/api/drafts/users" | "/api/drafts/validate-source" | "/api/scoring-settings" | "/api/snapshot" | "/api/snapshot-status"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/account": {}
  "/api/admin/sync-leaguepedia": {}
  "/api/chat": {}
  "/api/chat/metrics": {}
  "/api/chat/reactions": {}
  "/api/chat/upload": {}
  "/api/cron/drafts": {}
  "/api/drafts": {}
  "/api/drafts/[draftId]": { "draftId": string; }
  "/api/drafts/[draftId]/pick": { "draftId": string; }
  "/api/drafts/[draftId]/presence": { "draftId": string; }
  "/api/drafts/[draftId]/status": { "draftId": string; }
  "/api/drafts/metrics": {}
  "/api/drafts/users": {}
  "/api/drafts/validate-source": {}
  "/api/scoring-settings": {}
  "/api/snapshot": {}
  "/api/snapshot-status": {}
  "/auth": {}
  "/drafts": {}
  "/drafts/[draftId]": { "draftId": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
