// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/drafts/[draftId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drafts/[draftId]">> = Specific
  const handler = {} as typeof import("../../../src/app/drafts/[draftId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/drafts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/drafts">> = Specific
  const handler = {} as typeof import("../../../src/app/drafts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account">> = Specific
  const handler = {} as typeof import("../../../src/app/api/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/sync-leaguepedia/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sync-leaguepedia">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/sync-leaguepedia/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/metrics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/reactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/reactions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/reactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/chat/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/chat/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/cron/drafts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/drafts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/cron/drafts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/[draftId]/pick/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/[draftId]/pick">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/[draftId]/pick/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/[draftId]/presence/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/[draftId]/presence">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/[draftId]/presence/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/[draftId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/[draftId]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/[draftId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/[draftId]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/[draftId]/status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/[draftId]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/metrics">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/drafts/validate-source/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/drafts/validate-source">> = Specific
  const handler = {} as typeof import("../../../src/app/api/drafts/validate-source/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/scoring-settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/scoring-settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/scoring-settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/snapshot-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/snapshot-status">> = Specific
  const handler = {} as typeof import("../../../src/app/api/snapshot-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/snapshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/snapshot">> = Specific
  const handler = {} as typeof import("../../../src/app/api/snapshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
